[lib]
crate-type = ["dylib"]

[package]
name = "hello"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <wif.mboehm@gmx.de>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
postgres = "0.15"

